### ISSUE TITLE
don't make a name mandatory, when it actually is not

### ISSUE THREAD

**Issue by DJCrashdummy** [drcheap/WindowSizer#10]
perhaps it is just me because my old addon for this task had just a simple list with window resolutions and nothing more, so i don't need any names at all... but then i read as answer at a review the "workaround", to simply use a `space` as name.
but why making a name mandatory which obviously isn't, and then provide a workaround...?

if there is an other reason for a mandatory name, i would suggest to simply insert the `space` automatically if no name is entered and not bother the user with this. or alternatively use the resolution also as name... but that's questionable how much sense the same size twice side by side makes. not to mention, if the size gets edited at some point, it would become a mess.

**Comment by drcheap** [comment]
I can't remember off the top of my head why it was made mandatory, but I think there was a technical reason for it.
I will verify that this is actually the case, and if it truly can be made optional, I will remove the requirement.
