### ISSUE TITLE
Viewport Needs To Take Into Account The Sidebar Size

### ISSUE THREAD

**Issue by kenreeser** [drcheap/WindowSizer#12]
You've developed a fantastic plug-in. It would be perfect if it would take into account the size of a revealed sidebar. Currently, it treats the entire window—including the sidebar as the viewport size.

**Comment by drcheap** [comment]
Hmm.  I'm not sure if a web extension has the ability to detect and/or measure the size of a sidebar to compensate for that.  I will look further into this to see if that is even something possible to deal with.

**Comment by drcheap** [comment]
I've been looking, and there doesn't seem to be any way to determine the size of a sidebar, or even if one is open.

Doesn't look like this is possible.  If someone can point me at an API or function that gives me the width of a sidebar, I'll re-open.

**Comment by kenreeser** [comment]
I appreciate you looking into it. By the way, GIT shows I submitted this way back in September. That's incorrect. I just submitted this about a week ago (possibly 2 weeks ago). Not sure why the incorrect date was recorded
