### ISSUE TITLE
Can't create custom window sizes

### ISSUE THREAD

**Issue by Jim-Simpson** [drcheap/WindowSizer#20]
I am unable to set up custom sizes. First, there's no icon to use to get to that point. But I can get to a popup that lets me choose the one existing size, or choose to customize. Clicking on "Customize" does nothing. What am I doing wrong?

**Comment by drcheap** [comment]
If you navigate to **about:addons**, find WindowSizer on the list & choose the **...** menu, and then choose **Options**.  This should give you the options page that allows defining your presets.

The Customize... from the popup is supposed to lead to this same page, not sure why it isn't for you.


https://user-images.githubusercontent.com/10265909/232972639-71417fdf-6d4d-4ec1-af41-dfaf87df9e6d.mp4

**Comment by Jim-Simpson** [comment]
This worked, but since I can't change the position of the window, I don't really need it. Thanks for you help!
