### ISSUE TITLE
Ability to change hotkey

### ISSUE THREAD

**Issue by Dehumanizer77** [drcheap/WindowSizer#6]
It would be extremely helpful if one could edit the hotkey for each preset. Currently I have something else bind to alt+1 to alt+4 which I use frequently so I can't use hotkeys for the first 4 presets.

**Comment by drcheap** [comment]
I definitely want to offer this, but unfortunately at this time there isn't a way to do this.  See [Mozilla Bug 1303384](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384) for more details.  Once that issue is resolved, this should be possible without any additional development.

**Comment by drcheap** [comment]
Good news, it looks like the aforementioned roadblock has been fixed in the FF nightly, and is slated for release in less than a month in FF 66.  Based on the way they implemented it, there may not even need to be an update to WindowSizer.

Either way, it's coming soon!

**Comment by drcheap** [comment]
Hooray, you can now [manage extension shortcuts](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox) in Firefox!

I'll be updating the UI to better reflect this new feature.

**Comment by drcheap** [comment]
Commit ref: f8d819668a71ca66c3a639f082dda36e50f92b04
