### ISSUE TITLE
please make it possible to use presets bigger than the current screen

### ISSUE THREAD

**Issue by DJCrashdummy** [drcheap/WindowSizer#8]
sometimes i take a screenshot of a site via [*Save Screenshot*](https://addons.mozilla.org/firefox/addon/savescreenshot/) and i want them to fit a usual pixel-size resp. at least a usual pixel-width (that's mainly why i use *WindowSizer*).
but as soon as i use a smaller screen (e.g. on my notebook) it gets pretty tedious - because i have to store the site elsewhere and remember to take the screenshot later on my machine with the big screen - because *WindowSizer* does not allow sizes which are bigger than the current actual screen. :frowning_face: 

and yes... i tried to workaround by manually making the window size bigger than the screen (which is shown correctly at the *"Current Size"* of *WindowSizer*) and then apply the preset via the *"Current Window Size"*, but *WindowSizer* refuses it with a red frame & *"Please correct errors"*.

btw: even if you use the max. size shown as *"Current Window Size"* while the window is maximized, the actual size afterwards (shown in *"Current Size"*) is smaller than the preset. - i know this is because of the window frame, but also here again: why restricting it to the screen size?!?

**Comment by drcheap** [comment]
IIRC the very first version let you go up to screen size.  Then [later I added an "OVERSIZE_ALLOWANCE" constant](https://github.com/drcheap/WindowSizer/commit/81b5581658dd6cb86127a1e690250e0d430e5da9) to allow for more.  I think this had to do with window frames or dealing with other DWM sillyness.  I honestly don't remember the details, or exactly where I came up with the "10%" value that it currently uses.

So yeah, it should not really be quite so restrictive, but I do think there needs to be some kind of practical hard limit.  Don't need someone to think it's a good idea to slap a pile of 9s in the box, cause havoc with their browser, and then blame my crappy code ;)

I'll give this a bit of thought and see what I can do.

**Comment by drcheap** [comment]
Implemented!

**Comment by DJCrashdummy** [comment]
> Then later I added an "OVERSIZE_ALLOWANCE" constant to allow for more.

ok, that explains a lot... because after opening this issue i figured out, that a preset "some" pixel bigger than the actual screen was allowed, but still useless because after using it, the window size was still restricted to the screen size. :unamused: but besides i'm currently pretty busy, i decided as puzzled as i was, to leave this issue alone and wait if you are open to it in general.

> I honestly don't remember the details, or exactly where I came up with the "10%" value that it currently uses.

perhaps  because the height is not shown correctly on my machine. - e.g. instead of 900px the *"Detected Screen Size"* shows 864px. and 36px is exacly the height of my taskbar. :thinking: 

> Don't need someone to think it's a good idea to slap a pile of 9s in the box, cause havoc with their browser, and then blame my crappy code ;)

you are too kind, making software with integrated dumbass self-protection... :wink: but well, it's called **WindowS**izer, so it shouldn't be a surprise. :rofl: 

> Implemented!

thank you! that was quick! :ok_hand: 
unfortunately i have to report, that it is a little bit fiddly, because after changing the advanced settings you have to exit the addon-settings to get them applied. so if you experience the *"Please correct errors"* (because of a too big window size), you have to exit the settings and start again. - this is not a big issue **if known**, but would be better if it's not necessary. else i would at least mention it at the *"Advanced Settings"* area, because i was about to give up and report a bug.
